

name: Deploy React app to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # chạy mỗi khi push/merge vào nhánh main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build React app
        run: |
          cd SE19B01_Group4/react-app
          npm install
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IELTSPHOBIC }}
          channelId: live
          projectId: ieltsphobic
          entryPoint: SE19B01_Group4/react-app
